version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=mysql://pomodoro:pomodoro@db:3306/pomodoro
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: pomodoro
      MYSQL_DATABASE: pomodoro
      MYSQL_USER: pomodoro
      MYSQL_PASSWORD: pomodoro
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
