version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=mysql://pomodoro:pomodoro@sp_2405-db-1:3306/pomodoro
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:3306", "--", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pomodoro
      MYSQL_DATABASE: pomodoro
      MYSQL_USER: pomodoro
      MYSQL_PASSWORD: pomodoro
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
